// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// import Providers from "@/app/providers";

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }
import Providers from "./providers";

export const metadata = {
  title: "SPK Operator Kontrak",
  description:
    "Sistem Pendukung Keputusan Penentuan Karyawan Kontrak Menjadi Karyawan Tetap",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
